I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/screens.rpy", line 395, in execute
    screen main_menu():
  File "game/screens.rpy", line 395, in execute
    screen main_menu():
  File "game/screens.rpy", line 413, in execute
    vbox:
  File "game/screens.rpy", line 419, in execute
    if main_menu and mm2 == False:
  File "game/screens.rpy", line 421, in execute
    imagemap:
  File "game/screens.rpy", line 424, in execute
    imagebutton:
Exception: Imagebutton does not have a idle image. (auto='gui/mmtbns/ng_%s.png').

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\python.py", line 1184, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\core.py", line 2218, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\core.py", line 2748, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\core.py", line 2748, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\screen.py", line 700, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 395, in execute
    screen main_menu():
  File "game/screens.rpy", line 395, in execute
    screen main_menu():
  File "game/screens.rpy", line 413, in execute
    vbox:
  File "game/screens.rpy", line 419, in execute
    if main_menu and mm2 == False:
  File "game/screens.rpy", line 421, in execute
    imagemap:
  File "game/screens.rpy", line 424, in execute
    imagebutton:
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ui.py", line 975, in _imagebutton
    idle = choice(idle, idle_image, "idle", required=True)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ui.py", line 969, in choice
    raise Exception("Imagebutton does not have a %s image. (auto=%r)." % (name, auto))
Exception: Imagebutton does not have a idle image. (auto='gui/mmtbns/ng_%s.png').

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.6.25022803
Aperture Dating Simulator 1.1.6pt
Sat Oct  4 10:48:07 2025
